---
name: "Build"

on:
  push:
    branches:
      - main
    paths:
      - yamllint/Dockerfile
      - .github/workflows/yamllint.yaml

permissions:
  contents: 'read'
  id-token: 'write'
  packages: write

jobs:
  scan:
    runs-on: ubuntu-latest
    name: "[SCAN] kics"
    steps:
      - name: Mkdir results-dir
        run: mkdir -p results-dir
      - name: Checkout
        uses: actions/checkout@v3
      - name: 'run kics Scan'
        uses: checkmarx/kics-github-action@v2.1.3
        with:
          path: 'yamllint'
          token: ${{ secrets.GITHUB_TOKEN }}
          enable_comments: true
          exclude_queries: 'd3499f6d-1651-41bb-a9a7-de925fea487b'
          output_path: results-dir
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results-dir/results.sarif
  packaging:
    strategy:
      fail-fast: false
      matrix:
        version: ['1.0.0']
        latest: [true]
    runs-on: ubuntu-latest
    name: "[Build] Yaml Lint"
    steps:
      - name: Checkout
        uses: "actions/checkout@v3"

      - name: Login to GitHub Container Registry
        uses: 'docker/login-action@v1'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_REPOSITORY_TOKEN }}

      - name: Process builder
        shell: bash
        run: |
          echo "build_date=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_ENV

      - name: Set up Depot CLI
        uses: 'depot/setup-action@v1'

      - name: Build and Push Package
        uses: 'depot/build-push-action@v1'
        with:
          project: ${{ secrets.DEPOT_PROJECT_ID }}
          token: ${{ secrets.DEPOT_PROJECT_TOKEN }}
          push: true
          provenance: false
          sbom: false
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/devgine/yamllint:${{ matrix.version }}
            ${{ matrix.latest && 'ghcr.io/devgine/yamllint:latest' || ''}}
          context: .
          file: ./Dockerfile
          build-args: |
            VCS_REF=${{ github.sha }}
            BUILD_DATE=${{ env.build_date }}
            BUILD_VERSION=v${{ matrix.version }}
            IMAGE_TAG=ghcr.io/devgine/yamllint:${{ matrix.version }}
